<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Madina Seidualy">

<title>data-analysis-replication</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data-analysis-replication_files/libs/clipboard/clipboard.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/quarto.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/popper.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/anchor.min.js"></script>
<link href="data-analysis-replication_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data-analysis-replication_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">data-analysis-replication</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Madina Seidualy </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="data-analysis-replication-pca-and-welchs-t-test" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis-replication-pca-and-welchs-t-test">Data Analysis Replication: PCA and Welch’s t-test”</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/madinaseidualy/Desktop/Data_Analyses/Repo/replication_research"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">fig.path =</span> <span class="st">"images/"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report replicates parts of the statistical analyses from the study</p>
<ul>
<li>Juhyeon Lee&nbsp;<em>et al.</em> Genetic population structure of the Xiongnu Empire at imperial and local scales.<em>Sci. Adv.</em><strong>9</strong>,eadf3904(2023).DOI:<a href="https://doi.org/10.1126/sciadv.adf3904">10.1126/sciadv.adf3904</a></li>
</ul>
<p>The goal of this paper was to understand how genetic diversity was organized within the Xiongnu Empire (nomadic empire in late Iron age and historical era), especially at the local level and across different social statuses. The authors studied genome-wide data from 18 individuals buried in aristocratic and elite cemeteries at the western edge of the empire. Their analyses included PCA, genetic relatedness, admixture modeling and statistical tests to compare ancestry differences between individuals. They found that even within small communities, the genetic diversity was very high, just like across the whole empire. Low-status individuals were the most diverse, while high-status people were more similar to each other.</p>
<p>I replicated the following:</p>
<ul>
<li>Principal Component Analysis (PCA) with ancient and modern samples</li>
<li>PCA Visualization matching paper’s Figure 3A</li>
<li>Inferential statistical analyses using Welch’s t-test and Brown-Forsythe test</li>
</ul>
<p>I chose this paper because it aligns closely with my own research interests — it works with ancient DNA and focuses on Eurasian populations, the Xiongnu. What I really liked is that the study didn’t stop at PCA. They went further and applied statistical tests after PCA, comparing groups by sociopolitical status and by burial site. This gave me a new approach that I can actually test hypotheses statistically after the PCA using the result of it for checking whether elites have different ancestry patterns or whether variation differs by site. It’s a good direction that I think I can apply to my own data.</p>
<p>Overall: The original study used the Human Origins dataset (v54.1.p1_HO_public) merged with new TAK_SBB.1240K samples. The merged data included 500,000 SNPs and over 20,000 individuals in EIGENSTRAT format. I subsetted and visualized PCA projections and statistically tested genetic diversity between social status groups and archaeological sites.</p>
</section>
<section id="data-discovery-process-and-challenges" class="level2">
<h2 class="anchored" data-anchor-id="data-discovery-process-and-challenges">Data Discovery Process and Challenges</h2>
<p>The paper cited older publications for the Human Origins (HO) dataset but did not directly provide download links. I traced the original reference to the 2014 paper, <em>“Ancient human genomes suggest three ancestral populations for present-day Europeans”</em> , where Supplementary Information 9 (SI9) on page 60 states:</p>
<blockquote class="blockquote">
<p>“A total of 2,244 samples (of the 2,722) are in a version of the dataset we have made freely available at <a href="http://genetics.med.harvard.edu/reichlab/Reich_Lab/Datasets.html.”" class="uri">http://genetics.med.harvard.edu/reichlab/Reich_Lab/Datasets.html.”</a></p>
</blockquote>
<p>However, the URL is outdated and no longer functional. I wish the authors had included a direct and updated link to the data. To resolve this, I contacted Dr.&nbsp;Ainash Childebayeva, who provided the current official data source:</p>
<p><a href="https://reich.hms.harvard.edu/allen-ancient-dna-resource-aadr-downloadable-genotypes-present-day-and-ancient-dna-data" class="uri">https://reich.hms.harvard.edu/allen-ancient-dna-resource-aadr-downloadable-genotypes-present-day-and-ancient-dna-data</a></p>
<p>From this website, I downloaded the <strong>v54.1.p1_HO_public</strong> dataset, which contains:</p>
<ul>
<li>20,503 individuals (.ind file)</li>
<li>597,573 SNPs (.snp file)</li>
<li>Genotypes in EIGENSTRAT format (.geno file)</li>
</ul>
<p>The paper provided their new samples in eigenstrat format data:</p>
<p>“The genotype data for the 1240K panel have been deposited in the Edmond Data Repository of the Max Planck Society [<a href="https://doi.org/10.17617/3.DYCH7D" class="uri">https://doi.org/10.17617/3.DYCH7D</a>].” (from paper)</p>
<p>I downloaded the data into TAK_SBB.1240K folder.</p>
</section>
<section id="preparing-input-data" class="level2">
<h2 class="anchored" data-anchor-id="preparing-input-data">Preparing Input Data</h2>
<section id="read-.ind-file-from-ho-dataset" class="level3">
<h3 class="anchored" data-anchor-id="read-.ind-file-from-ho-dataset">Read .ind file from HO dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ind <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"data/v54.1.p1_HO_public/v54.1.p1_HO_public.ind"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character(),
  X2 = col_character(),
  X3 = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ind) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ID"</span>, <span class="st">"Sex"</span>, <span class="st">"Pop"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ind)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20503     3</code></pre>
</div>
</div>
</section>
<section id="filter-populations-for-pca" class="level3">
<h3 class="anchored" data-anchor-id="filter-populations-for-pca">Filter populations for PCA</h3>
<p>I used the paper’s Supplementary Table S1B to extract the populations used for PCA (<code>PCA_used.csv</code>) - contains list of the population used for PCA and their dataset.</p>
<p>From there I extracted the list of the populations, mostly modern populations and only few ancient populations – like Xiongnu period samples – as its related to the study research samples; and I kept less due to computation capacity – worried to crash my computer (however, anyway crashed)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pop_table <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/PCA_used.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 321 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Analysis.Group.Label, Ancient, 1240K dataset, HO dataset, PCA
dbl (1): N

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pca_pops <span class="ot">&lt;-</span> pop_table <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PCA <span class="sc">==</span> <span class="st">"O"</span>, <span class="st">`</span><span class="at">HO dataset</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"O"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Analysis.Group.Label)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(pca_pops)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 159</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#from the table where they provided the information which populatioin used for PCA and from which dataset, I extracted where PCA column is O and HO is O;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pca_pops)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Chandman_IA"        "earlyXiongnu_rest"  "earlyXiongnu_west" 
[4] "eastMongolia_preBA" "lateXiongnu"        "lateXiongnu_han"   </code></pre>
</div>
</div>
<p>159 population in total used for PCA analyses;</p>
</section>
<section id="check-matching-populations" class="level3">
<h3 class="anchored" data-anchor-id="check-matching-populations">Check matching populations</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>matching_inds <span class="ot">&lt;-</span> ind <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">sapply</span>(Pop, <span class="cf">function</span>(popname) <span class="fu">any</span>(<span class="fu">str_detect</span>(popname, pca_pops))))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># from big dataset, matching how many individuals used for PCA analyses  </span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(matching_inds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5400    3</code></pre>
</div>
</div>
<p>5499 indiviuals is so many for analysese so I wanted to cut for the 5 individual per population group Sampling 5 individuals per group for PCA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>subset_inds_1 <span class="ot">&lt;-</span> matching_inds <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Pop) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(subset_inds_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2573    3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset_inds_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ID           Sex   Pop              
  &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;            
1 KCHE-1032.HO M     Abazin.HO        
2 KCHE-1283.HO M     Abazin.HO        
3 KCHE-1294.HO M     Abazin.HO        
4 KCHE-1330.HO M     Abazin.HO        
5 KCHE-1333.HO M     Abazin.HO        
6 KCHE-1052.HO M     Abazin_outlier.HO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span>(<span class="st">"outlier"</span>, subset_inds_1<span class="sc">$</span>Pop, <span class="at">value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Abazin_outlier.HO"                              
 [2] "Abazin_outlier.HO"                              
 [3] "Avar_outlier1.HO"                               
 [4] "Avar_outlier2.HO"                               
 [5] "Greek_outlier.WGA.HO"                           
 [6] "Greek_outlier.WGA.HO"                           
 [7] "Ignore_Altaian_PCA_outlier.HO"                  
 [8] "Ignore_Buryat_PCA_outlier.HO"                   
 [9] "Ignore_Buryat_PCA_outlier.HO"                   
[10] "Ignore_Dungan_PCA_outlier.HO"                   
[11] "Ignore_Evenk_PCA_outlier.HO"                    
[12] "Ignore_Evenk_PCA_outlier.HO"                    
[13] "Ignore_Evenk_PCA_outlier.HO"                    
[14] "Ignore_Kurdish_PCA_outlier.HO"                  
[15] "Ignore_Negidal_PCA_outlier.HO"                  
[16] "Ignore_Nganasan_PCA_outlier.HO"                 
[17] "Ignore_Russian_PCA_outlier.HO"                  
[18] "Ignore_Russian_PCA_outlier.HO"                  
[19] "Ignore_Tatar_Siberian_PCA_outlier.HO"           
[20] "Ignore_Todzin_PCA_outlier.HO"                   
[21] "Ignore_Tubalar_PCA_outlier.HO"                  
[22] "Ignore_Turkish_Balikesir_PCA_outlier_vs_rest.HO"
[23] "Ignore_Yukagir_Tundra_PCA_outlier.HO"           
[24] "Ignore_Yukagir_Tundra_PCA_outlier.HO"           
[25] "Ignore_Yukagir_Tundra_PCA_outlier.HO"           
[26] "Ignore_Yukagir_Tundra_PCA_outlier.HO"           
[27] "Ignore_Yukagir_Tundra_PCA_outlier.HO"           
[28] "Kabardinian_outlier.HO"                         
[29] "Khakass_outlier.HO"                             
[30] "Turkmen_outlier.HO"                             
[31] "Uzbek_outlier.WGA.HO"                           </code></pre>
</div>
</div>
<p>Now the individual numbers are fell down to 2638 individuals. [still a lot]</p>
<p>When, I did head(subset_inds_1), noticed that there are outliers, that matched the population name. So I have to exclude them, since they are not in the PCA analyses either;</p>
<p>My $pca_pop list has names like “French”, “Abazin”, “Kazakh”</p>
<p>While ind$Pop column has entries like “French.HO”, “Abazin.HO”, “Kazakh.HO”. (so I used str_detect my popname, but its matching to everything_additionals, like ignore/outlier cases)</p>
<p>So doing different way filtering the data - before matching, removing .HO/DG extension then filtering</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>matching_inds <span class="ot">&lt;-</span> ind <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_remove</span>(Pop, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>) <span class="sc">%in%</span> pca_pops)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(matching_inds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ID         Sex   Pop        
  &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;      
1 ABA-035.HO M     Karachai.HO
2 ABA-048.HO M     Karachai.HO
3 ABA-052.HO M     Karachai.HO
4 ABA-056.HO M     Karachai.HO
5 ABA-065.HO M     Karachai.HO
6 ABA-069.HO M     Karachai.HO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>subset_inds_2 <span class="ot">&lt;-</span> matching_inds <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Pop) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(subset_inds_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 850   3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset_inds_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ID           Sex   Pop         
  &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;       
1 KCHE-1032.HO M     Abazin.HO   
2 KCHE-1283.HO M     Abazin.HO   
3 KCHE-1294.HO M     Abazin.HO   
4 KCHE-1330.HO M     Abazin.HO   
5 KCHE-1333.HO M     Abazin.HO   
6 abh27.HO     M     Abkhasian.HO</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#now much less individuals</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#this one to check which populations did not match with big dataset of individuals</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>all_pops <span class="ot">&lt;-</span> <span class="fu">unique</span>(subset_inds_2<span class="sc">$</span>Pop)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">sapply</span>(pca_pops, <span class="cf">function</span>(p) <span class="fu">any</span>(<span class="fu">str_detect</span>(all_pops, p)))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(pca_pops[<span class="sc">!</span>matched])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I wanted to check which populatiion groups are not in the dataset</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>pca_pops[<span class="sc">!</span>matched]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Chandman_IA"           "earlyXiongnu_rest"     "earlyXiongnu_west"    
 [4] "eastMongolia_preBA"    "lateXiongnu"           "lateXiongnu_han"      
 [7] "lateXiongnu_sarmatian" "Ulaanzuukh_SlabGrave"  "Aleut_Tlingit"        
[10] "Altaian_Chelkans"      "Borneo"                "German"               
[13] "Irish"                 "Irish_Ulster"          "Khakass_Kachins"      
[16] "Lahu"                  "Semende"               "Shetlandic"           
[19] "Sorb"                  "Yukagir"              </code></pre>
</div>
</div>
<p>As noticed, most of the ancient population groups do not match - the Suplementary table pop names have different population names with the v54.1 dataset.</p>
<p>It’s so confusing there is no consistency between population names and their labelling. Some of them had ending with .HO, while some .DG. while the suplementary table just population names - it was hard to filter and extract desired populations.</p>
<p>The paper grouped some individuals into population groups like “earlyXiongnu” and “lateXiongnu”. In the supplementary file S1B they provided which group has which individuals, so I extracted those groupings manually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Here when looked into dataset those populatioin names do not exist, but individuals that belong that population exist, so they just have different names</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span>(<span class="st">"earlyXiongnu"</span>, ind<span class="sc">$</span>Pop, <span class="at">value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grep</span>(<span class="st">"lateXiongnu"</span>, ind<span class="sc">$</span>Pop, <span class="at">value =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ind[<span class="fu">grep</span>(<span class="st">"JAG001"</span>, ind<span class="sc">$</span>ID), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  ID     Sex   Pop                     
  &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;                   
1 JAG001 M     Mongolia_Khentii_Xiongnu</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/sciadv_f3_PCA.jpg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/sciadv_f3_PCA.jpg" class="img-fluid figure-img" width="2160"></p>
</figure>
</div>
</div>
</div>
<p>In PCA plot from the paper, there is Early and LATE xiongnu groups ONLY, while in the SI table:</p>
<pre><code>"earlyXiongnu_rest"     "earlyXiongnu_west" "lateXiongnu"           "lateXiongnu_han"       "lateXiongnu_sarmatian" </code></pre>
<p>So I am going to rename populations that have those individuals to Early and Late_Xiongnu, respectively Defining Xiongnu groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>xiongnu_groups <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">earlyXiongnu =</span> <span class="fu">c</span>(<span class="st">"JAG001"</span>, <span class="st">"SKT002"</span>, <span class="st">"SKT004"</span>, <span class="st">"SKT005"</span>, <span class="st">"SKT006"</span>, <span class="st">"SKT012"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"AST001"</span>, <span class="st">"SKT001"</span>, <span class="st">"SKT003"</span>, <span class="st">"SKT008"</span>, <span class="st">"SKT009"</span>, <span class="st">"SKT010"</span>),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">lateXiongnu =</span> <span class="fu">c</span>(<span class="st">"SAN001"</span>, <span class="st">"UGU004"</span>, <span class="st">"SOL001"</span>, <span class="st">"DEL001"</span>, <span class="st">"ULN004"</span>, <span class="st">"BTO001"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"CHN010"</span>, <span class="st">"DOL001"</span>, <span class="st">"EME002"</span>, <span class="st">"JAA001"</span>, <span class="st">"KHO007"</span>, <span class="st">"TEV002"</span>, <span class="st">"TUK003"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"UGU011"</span>, <span class="st">"UVG001"</span>, <span class="st">"TEV003"</span>, <span class="st">"IMA001"</span>, <span class="st">"IMA002"</span>, <span class="st">"IMA003"</span>, <span class="st">"IMA004"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"IMA005"</span>, <span class="st">"IMA006"</span>, <span class="st">"IMA007"</span>, <span class="st">"IMA008"</span>, <span class="st">"ATS001"</span>, <span class="st">"BAM001"</span>, <span class="st">"BRU001"</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"KHO006"</span>, <span class="st">"SON001"</span>, <span class="st">"TUH001"</span>, <span class="st">"TUH002"</span>, <span class="st">"TUK002"</span>,<span class="st">"TMI001"</span>, <span class="st">"BUR001"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"NAI001"</span>, <span class="st">"BUR002"</span>, <span class="st">"BRL002"</span>,<span class="st">"BUR003"</span>,<span class="st">"BUR004"</span>, <span class="st">"DUU001"</span>, <span class="st">"HUD001"</span>,</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"NAI002"</span>,<span class="st">"UGU005"</span>, <span class="st">"UGU006"</span>, <span class="st">"UGU010"</span>)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="co">#created the list of the populations and turning into dataframe with each ID there is assigned Population name</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>xiongnu_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">names</span>(xiongnu_groups), <span class="cf">function</span>(group) {</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">ID =</span> xiongnu_groups[[group]], <span class="at">Group =</span> group)</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(xiongnu_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  ID     Group       
  &lt;chr&gt;  &lt;chr&gt;       
1 JAG001 earlyXiongnu
2 SKT002 earlyXiongnu
3 SKT004 earlyXiongnu
4 SKT005 earlyXiongnu
5 SKT006 earlyXiongnu
6 SKT012 earlyXiongnu</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#xiongnu_df is the list of individuals I want to extract for big dataset .ind</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>xiongnu_inds <span class="ot">&lt;-</span> ind <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(xiongnu_df, <span class="at">by =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, Sex, <span class="at">Pop =</span> Group)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co">#xiongnu_inds is the ones extracted from the bigdataset, in totall 57 inds belong to the Xiongnu</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(xiongnu_inds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ID     Sex   Pop        
  &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;      
1 HUD001 F     lateXiongnu
2 NAI001 M     lateXiongnu
3 NAI002 M     lateXiongnu
4 SOL001 F     lateXiongnu
5 EME002 F     lateXiongnu
6 BUR003 M     lateXiongnu</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(xiongnu_inds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 57  3</code></pre>
</div>
</div>
</section>
<section id="saving-the-subset-list-of-individuals-into-separate-file" class="level3">
<h3 class="anchored" data-anchor-id="saving-the-subset-list-of-individuals-into-separate-file">Saving the subset list of individuals into separate file</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>subset_inds <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(subset_inds_2,xiongnu_inds) </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(subset_inds, <span class="st">"data/HO_pca_subset_list.ind"</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">col.names =</span> <span class="cn">FALSE</span>, <span class="at">quote =</span> <span class="cn">FALSE</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I wanted to read original big dataset .geno line-by-line and extract only the selected columns associated with individuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#infile &lt;- file("data/v54.1.p1_HO_public/v54.1.p1_HO_public.geno", "r")</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co"># .geno file consist of large dataset with 500K rows for 20000 individuals, there I had to extract the information of individuals I made list above; at first I have to extract the indexes of their order from .ind file, and then .geno get that column information.</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co">#outfile &lt;- file("HO_pca_subset.geno", "w")</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co">#keep_inds &lt;- which(ind$ID %in% subset_inds_2$ID)</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="co">#while(length(line &lt;- readLines(infile, n = 1)) &gt; 0) {</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  genos &lt;- strsplit(line, "")[[1]]</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  filtered_genos &lt;- genos[keep_inds]</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co">#  writeLines(paste0(filtered_genos, collapse = ""), outfile)</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="co">#  }</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co">#close(infile)</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="co">#close(outfile)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, it didn’t work, I could not load .geno at all to my computer, at first I thought .geno is only 3 GB – as was shown at website, but it came out it was binary file – I have to convert it – kind of unzip – using plink program (explain plink) – which wasn’t mentioned in any methods – here I stuck also so much!</p>
<p>Then I had to use server, there I found that it’s non-binary file size is 28GB, so its impossible to run it in my computer or in R – due to my RAM is only 16GB.</p>
<p>-&gt; I wish they could provide the option to chose populations data set, that we want to extract/download from the website - otherwise all of them are so big to do download and data manipulations;</p>
<p>The New samples data, which was provided by paper with 17 individuals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tak_ind <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"data/TAK_SBB.1240K/TAK_SBB.1240K.ind"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character(),
  X2 = col_character(),
  X3 = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tak_ind) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ID"</span>, <span class="st">"Sex"</span>, <span class="st">"Pop"</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tak_ind)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17  3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tak_ind)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  ID           Sex   Pop         
  &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;       
1 SBB003.A0101 F     SBB003.A0101
2 SBB006.A0101 F     SBB006.A0101
3 SBB007.A0101 F     SBB007.A0101
4 SBB010.A0101 M     SBB010.A0101
5 TAK002.A0101 F     TAK002.A0101
6 TAK005.A0101 M     TAK005.A0101</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>tak_snp <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"data/TAK_SBB.1240K/TAK_SBB.1240K.snp"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character(),
  X2 = col_double(),
  X3 = col_double(),
  X4 = col_double(),
  X5 = col_character(),
  X6 = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>ho_snp <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"data/v54.1.p1_HO_public/v54.1.p1_HO_public.snp"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  X1 = col_character(),
  X2 = col_double(),
  X3 = col_double(),
  X4 = col_double(),
  X5 = col_character(),
  X6 = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ho_snp) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(tak_snp) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"rsid"</span>, <span class="st">"chrom"</span>, <span class="st">"gen_pos"</span>, <span class="st">"phys_pos"</span>, <span class="st">"ref"</span>, <span class="st">"alt"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ho_snp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 597573      6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tak_snp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1233013       6</code></pre>
</div>
</div>
<p>Therefore, I decided to do manipulations in server – big computer cluster – I merged the datasets of big HO and TAK from this paper into one dataset – big data was 500K HO data - while paper 1240K sites data. When we merge it will be 500K snp site information for all population and individuals including new study samples.</p>
</section>
</section>
<section id="merging-and-smartpca" class="level2">
<h2 class="anchored" data-anchor-id="merging-and-smartpca">Merging and SmartPCA</h2>
<p>I used mergeit from EIGENSOFT on the server to merge the HO and TAK_SBB datasets - same as in paper Methods:</p>
<hr>
</section>
<section id="mergeit--p-merge_param.txt" class="level2">
<h2 class="anchored" data-anchor-id="mergeit--p-merge_param.txt">mergeit -p merge_param.txt</h2>
<p>My parameter merge_param.txt file content:</p>
<hr>
<p>geno1: /mnt/archgen/public_data/AADR_V54.1_NOV2022_HO/v54.1_HO_public.geno snp1: /mnt/archgen/public_data/AADR_V54.1_NOV2022_HO/v54.1_HO_public.snp ind1: /mnt/archgen/public_data/AADR_V54.1_NOV2022_HO/v54.1_HO_public.ind geno2: /mnt/archgen/users/seidualy/replication/TAK_SBB.1240K.geno snp2: /mnt/archgen/users/seidualy/replication/TAK_SBB.1240K.snp ind2: /mnt/archgen/users/seidualy/replication/TAK_SBB.1240K.ind genooutfilename: v54_TAK_SBB_HO.geno snpoutfilename: v54_TAK_SBB_HO.snp indoutfilename: v54_TAK_SBB_HO.ind outputformat: EIGENSTRAT docheck: YES strandcheck: YES —</p>
<p>Then run on server, the mergeit funciton generated to me a big merged file.</p>
<p>Then I used smartpca with to replicate the PCA, as mentioned in the paper methods on population list I have generated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>combined <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(subset_inds, tak_ind)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ID"  "Sex" "Pop"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#combinig the new studya samles (TAK..) to our desired PCA pop list</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ExtractING the 3rd column (population names) AND geting unique sorted list saving into variable pops</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>pops <span class="ot">&lt;-</span> combined <span class="sc">|&gt;</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(Pop) <span class="sc">|&gt;</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sort</span>() <span class="sc">|&gt;</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>()</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Saving only population list to run smartpca</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a><span class="fu">write_lines</span>(pops, <span class="st">"PCA_pop.list"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="smartpca--p-pca.par" class="level2">
<h2 class="anchored" data-anchor-id="smartpca--p-pca.par">smartpca -p pca.par</h2>
<p>my pca.par parameter file content:</p>
<p>____________</p>
<p>genotypename: /mnt/archgen/users/seidualy/replication/v54_TAK_SBB_HO.geno snpname: /mnt/archgen/users/seidualy/replication/v54_TAK_SBB_HO.snp indivname: /mnt/archgen/users/seidualy/replication/v54_TAK_SBB_HO.ind evecoutname: /mnt/archgen/users/seidualy/replication/v54_TAK_SBB_HO_PCA.evec evaloutname: /mnt/archgen/users/seidualy/replication/v54_TAK_SBB_HO_PCA.eval poplistname: /mnt/archgen/users/seidualy/replication/PCA_pop.list lsqproject: YES</p>
<p>______________</p>
<p>Again I made an parameter file and run the pca using methods of EIGENSOFT from this website:</p>
<p><a href="https://github.com/roberta-davidson/ADMIXTURE-smartPCA-PLINK-and-EIGENSOFT/blob/main/README.md" class="uri">https://github.com/roberta-davidson/ADMIXTURE-smartPCA-PLINK-and-EIGENSOFT/blob/main/README.md</a></p>
<p>This produced <code>.evec</code> and <code>.eval</code> files with eigenvectors and values.</p>
<p>Here, I wanted to show the percentage of total variance explained by each principal component.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>eigen_df <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"data/v54_TAK_SBB_HO_PCA.eval"</span>, <span class="at">col_names =</span> <span class="st">"Eigenvalue"</span>) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  Eigenvalue = col_double()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(eigen_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  Eigenvalue
       &lt;dbl&gt;
1     145.  
2      16.7 
3       7.34
4       5.74
5       5.47
6       4.82</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>variance_explained <span class="ot">&lt;-</span> eigen_df<span class="sc">$</span>Eigenvalue<span class="sc">/</span><span class="fu">sum</span>(eigen_df<span class="sc">$</span>Eigenvalue) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(variance_explained, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 73.23  8.43  3.71  2.91  2.77  2.44  1.96  1.61  1.51  1.44</code></pre>
</div>
</div>
</section>
<section id="pca-visualization" class="level2">
<h2 class="anchored" data-anchor-id="pca-visualization">PCA Visualization</h2>
<p>For visualization I wanted to plot PCA plot, as shown in the paper image</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/sciadv_f3_PCA.jpg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/sciadv_f3_PCA.jpg" class="img-fluid figure-img" width="2160"></p>
</figure>
</div>
</div>
</div>
<p>Fig.3A. (A) Principal components analysis (PCA) of Takhiltyn Khotgor (TAK) (yellow squares) and Shombuuzyn Belchir (SBB) (red circles) individuals. Other Xiongnu individuals are shown as hollow diamonds (early Xiongnu) and black diamonds (late Xiongnu). Ancient individuals were projected on the PCs calculated with 2077 present-day Eurasian individuals (gray). Inset shows PC1 on the x-axis and PC3 on the y axis. PC3 explains the 0.33% of the total variance. The x axis and y axis ticks have the same values across all panels, except the inset of (A) where the y axis ranges from −0.04 to 0.06.</p>
<section id="load-and-plot-pca-output" class="level3">
<h3 class="anchored" data-anchor-id="load-and-plot-pca-output">Load and plot PCA output</h3>
<p>I am trying to generate the same PCA plot using my eigenvector data.</p>
<p>The PCA_pop.list data we have generated -&gt; I am making a table of information that ggplot use to color individuals of the population.</p>
<p>_____________________</p>
<p>The function of generating table was created to assign to every population a color and shape. I made just general table, so that it was convenient to change according to your desire.</p>
<p>It assign all .HO/DG ending populations as modern group - and to all of them grey circle with 0.8 transparency and size 1, while for others for now red square with size 2 - but by opening file I can adjust to certain pops different size and color;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>generate_marker <span class="ot">&lt;-</span> <span class="cf">function</span>(pops) {</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  unique_pops <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(pops))</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  style_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Pop =</span> unique_pops,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Group =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="st">"modern"</span>, unique_pops),</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Shape =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="dv">16</span>, <span class="dv">15</span>),         <span class="co"># circle for modern, square for others</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fill =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="st">"gray"</span>, <span class="st">"red"</span>),    <span class="co"># gray for modern, red for others</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Color =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="st">"gray"</span>, <span class="st">"black"</span>), <span class="co"># border color</span></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Size =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="dv">1</span>, <span class="dv">2</span>),          <span class="co"># default size for modern vs others</span></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Transparency =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(unique_pops, <span class="st">"</span><span class="sc">\\</span><span class="st">.(HO|DG)$"</span>), <span class="fl">0.8</span>, <span class="fl">1.0</span>)    <span class="co"># transparency</span></span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(style_table)</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reading The PCA evec data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>evecDat <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"data/v54_TAK_SBB_HO_PCA.evec"</span>, <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">"Sample"</span>,<span class="st">"PC1"</span>,<span class="st">"PC2"</span>,<span class="st">"PC3"</span>,<span class="st">"PC4"</span>,<span class="st">"PC5"</span>,<span class="st">"PC6"</span>,<span class="st">"PC7"</span>,<span class="st">"PC8"</span>,<span class="st">"PC9"</span>,<span class="st">"PC10"</span>,<span class="st">"Pop"</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pops -is previously assigned unique pops inlcuding PCA population including new samples</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>marker_df <span class="ot">&lt;-</span> <span class="fu">generate_marker</span>(pops)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="co"># SavING to CSV</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(marker_df, <span class="st">"data/PCA_marker_style.csv"</span>)</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a><span class="do">##this one is the backbone only, then I manually added different shaped for my interested populations and assigned </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I manually assigned different shapes for my groups to match similar plot from figure 1.A.</p>
<p>For individuals – SBB* - pop-names – red circle with black borders</p>
<p>For individuals – TAK* - pop-names – yellow rectangular with black border</p>
<p>Then early Xiongnu white kite. Then Late Xiongnu black kite,</p>
</section>
<section id="plot-pca-pc1-vs-pc2" class="level3">
<h3 class="anchored" data-anchor-id="plot-pca-pc1-vs-pc2">Plot PCA (PC1 vs PC2)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="do">###### Install the necessary packages</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("plotly")</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggplot2")</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggpubr")</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="do">###### load the necessary packages</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a><span class="co">#library(data.table)</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a><span class="co">#library(tidyverse)</span></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotly'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    last_plot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>keep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/PCA_pop_marker_plot.csv"</span>)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>evecDat_plotting <span class="ot">&lt;-</span> <span class="fu">merge</span>(evecDat, keep, <span class="at">by =</span> <span class="st">"Pop"</span>)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>evecDat_plotting <span class="ot">&lt;-</span> evecDat_plotting <span class="sc">|&gt;</span> <span class="fu">arrange</span>(Transparency) </span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a><span class="do">### to arrange visibility, less transparent on behind</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">as.character</span>(evecDat_plotting<span class="sc">$</span>Group)</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>shapes <span class="ot">&lt;-</span> evecDat_plotting<span class="sc">$</span>Shape</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">as.character</span>(evecDat_plotting<span class="sc">$</span>Color)</span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> evecDat_plotting<span class="sc">$</span>Size</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>transparency <span class="ot">&lt;-</span> evecDat_plotting<span class="sc">$</span>Transparency</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>fill <span class="ot">&lt;-</span> <span class="fu">as.character</span>(evecDat_plotting<span class="sc">$</span>Fill)</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>Sample_ID <span class="ot">&lt;-</span> <span class="fu">as.character</span>(evecDat_plotting<span class="sc">$</span>Sample)</span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Label only select individuals</span></span>
<span id="cb88-17"><a href="#cb88-17" aria-hidden="true" tabindex="-1"></a>label_points <span class="ot">&lt;-</span> evecDat_plotting <span class="sc">%&gt;%</span></span>
<span id="cb88-18"><a href="#cb88-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(Sample, <span class="st">"TAK"</span>) <span class="sc">|</span> <span class="fu">str_starts</span>(Sample, <span class="st">"SBB"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb88-19"><a href="#cb88-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label_x =</span> PC1 <span class="sc">+</span> <span class="fl">0.009</span>,</span>
<span id="cb88-20"><a href="#cb88-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">label_y =</span> PC2 <span class="sc">-</span> <span class="fl">0.03</span>)</span>
<span id="cb88-21"><a href="#cb88-21" aria-hidden="true" tabindex="-1"></a>label_points <span class="ot">&lt;-</span> label_points <span class="sc">%&gt;%</span></span>
<span id="cb88-22"><a href="#cb88-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CleanLabel =</span> <span class="fu">str_remove</span>(Sample, <span class="st">"</span><span class="sc">\\</span><span class="st">..*"</span>))  <span class="co"># Remove .A0101 or similar</span></span>
<span id="cb88-23"><a href="#cb88-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb88-24"><a href="#cb88-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-25"><a href="#cb88-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evecDat_plotting, <span class="fu">aes</span>(PC1, PC2)) <span class="sc">+</span> </span>
<span id="cb88-26"><a href="#cb88-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">shape=</span>samples, <span class="at">color=</span>samples, <span class="at">fill =</span> samples, <span class="at">size =</span> samples), <span class="at">alpha =</span> transparency)<span class="sc">+</span> </span>
<span id="cb88-27"><a href="#cb88-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PCA</span><span class="sc">\n</span><span class="st">"</span>,<span class="at">x=</span><span class="st">"PC 1"</span>,<span class="at">y=</span><span class="st">"PC 2"</span>) <span class="sc">+</span> </span>
<span id="cb88-28"><a href="#cb88-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> label_points,</span>
<span id="cb88-29"><a href="#cb88-29" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">xend =</span> label_x, <span class="at">yend =</span> label_y),</span>
<span id="cb88-30"><a href="#cb88-30" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb88-31"><a href="#cb88-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Place the labels</span></span>
<span id="cb88-32"><a href="#cb88-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> label_points,</span>
<span id="cb88-33"><a href="#cb88-33" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> label_x, <span class="at">y =</span> label_y, <span class="at">label =</span> CleanLabel),</span>
<span id="cb88-34"><a href="#cb88-34" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">2.0</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb88-35"><a href="#cb88-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> shapes)<span class="sc">+</span> </span>
<span id="cb88-36"><a href="#cb88-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> fill) <span class="sc">+</span> </span>
<span id="cb88-37"><a href="#cb88-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> colors) <span class="sc">+</span> </span>
<span id="cb88-38"><a href="#cb88-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> sizes) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb88-39"><a href="#cb88-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">7</span>), <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.99</span>),<span class="at">legend.justification =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"top"</span>),<span class="at">legend.key.size =</span> <span class="fu">unit</span>(<span class="fl">0.2</span>, <span class="st">"cm"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2
3.5.0.
ℹ Please use the `legend.position.inside` argument of `theme()` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"images/pca_replication1.png"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>PLOT PC1 and PC3. (in small box in fig3.A there is plot of PC1 to PC3)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evecDat_plotting, <span class="fu">aes</span>(PC1, <span class="sc">-</span>PC3)) <span class="sc">+</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">shape=</span>samples, <span class="at">color=</span>samples, <span class="at">fill =</span> samples, <span class="at">size =</span> samples), <span class="at">alpha =</span> transparency)<span class="sc">+</span> </span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PCA</span><span class="sc">\n</span><span class="st">"</span>,<span class="at">x=</span><span class="st">"PC 1"</span>,<span class="at">y=</span><span class="st">"PC 3"</span>) <span class="sc">+</span> </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> shapes)<span class="sc">+</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> fill) <span class="sc">+</span> </span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> colors) <span class="sc">+</span> </span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_manual</span>(<span class="at">name =</span> <span class="st">"Samples"</span>, <span class="at">breaks=</span>samples, <span class="at">labels =</span> samples,<span class="at">values=</span> sizes) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>),<span class="at">legend.position=</span><span class="st">"right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"images/pca_replication2.png"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">6</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical Analysis</h2>
<section id="group-by-social-status" class="level3">
<h3 class="anchored" data-anchor-id="group-by-social-status">Group by social status</h3>
<p>From paper:</p>
<p><em>Together, we observe a high degree of genetic heterogeneity and diversity at the elite sites of TAK and SBB, with the highest genetic heterogeneity observed among the lowest-status individuals. In contrast, we find that the highest-status individuals in this study, the aristocratic and local elite females, tended to be less diverse (P = 0.011 for Brown-Forsythe test to compare the PC1 variances of low-status and high-status individuals) with higher levels of eastern Eurasian ancestry. Eastern Eurasian ancestry is represented by the higher PC1 values and the mean of PC1 of the high-status individuals is significantly greater than that of the low-status individuals (P = 0.032 for one-sided Welch’s t test to test the null hypothesis that PC1 mean of high-status individuals is equal to that of low-status individuals). This suggests that elite status and power was disproportionately concentrated among individuals who traced their ancestry back to the preceding EIA Slab Grave groups.</em></p>
<p><em>On the basis of the broad distribution of SBB and TAK individuals along the PC1 axis, we find that each site is highly heterogeneous. To statistically compare the genetic diversity of each site and the Xiongnu as a whole (“all Xiongnu”), we applied the Brown-Forsythe test for the null hypothesis that two groups have equal PC1 variances (data file S1D). TAK is highly heterogeneous to the level indistinguishable from the variance across all Xiongnu individuals (P = 0.622), while SBB shows less diversity than all Xiongnu (P = 0.030).</em></p>
<p>Here, Authors use PC1 as a proxy for genetic ancestry (Eastern versus Western). To investigate whether there were differences in genetic ancestry between social status groups, they conducted two statistical tests on PC1 values.</p>
<p>There was not any table that providing which samples are high status which is low, except with word mentioning in the beginning part of the Results in the paper. But then I confirmed from the author that, whether what I picked from reading are all high status individuals.</p>
<p>The ones that belong to high status are (from Juhyen Lee):</p>
<p>SBB002</p>
<p>SBB003</p>
<p>SBB007</p>
<p>SBB008</p>
<p>TAK001</p>
<p>TAK002</p>
<p>I assigned these individuals to the “high” group, while all other SBB and TAK individuals I categorized as “low” status. At first, the ID of those samples had name.A10101 some extra extensions on the name, so I wanted to get rid of that then assign tags. [high or low]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>pca_df <span class="ot">&lt;-</span> evecDat <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SampleID =</span> <span class="fu">str_remove</span>(Sample, <span class="st">"</span><span class="sc">\\</span><span class="st">..*"</span>))</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="co">#removing extra writings after the dot .*</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>high_status_ids <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"SBB002"</span>, <span class="st">"SBB003"</span>, <span class="st">"SBB007"</span>, <span class="st">"SBB008"</span>, <span class="st">"TAK001"</span>, <span class="st">"TAK002"</span>)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>pca_df <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">Status =</span> <span class="fu">case_when</span>(</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  SampleID <span class="sc">%in%</span> high_status_ids <span class="sc">~</span> <span class="st">"high"</span>,</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_starts</span>(SampleID, <span class="st">"SBB"</span>) <span class="sc">|</span> <span class="fu">str_starts</span>(SampleID, <span class="st">"TAK"</span>) <span class="sc">~</span> <span class="st">"low"</span>,</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="co">#SBB or TAK those not in high status group labelled as low, and the rest population NA</span></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>status_test_df <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="welchs-t-test" class="level3">
<h3 class="anchored" data-anchor-id="welchs-t-test">Welch’s t-test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(PC1 <span class="sc">~</span> Status, <span class="at">data =</span> status_test_df, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PC1 by Status
t = 1.9831, df = 15.963, p-value = 0.03242
alternative hypothesis: true difference in means between group high and group low is greater than 0
95 percent confidence interval:
 0.0009878498          Inf
sample estimates:
mean in group high  mean in group low 
        0.01856667         0.01030000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#alternative = "greater" because the hypothesis was directional, not two-sided</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co">#high-status individuals were expected to show higher PC1 values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The test statistic was t = 1.98 with 15.963 degrees of freedom and a one-sided p-value of 0.03242. The 95% confidence interval for the difference in means was [0.00099, ∞), supporting the alternative hypothesis that high-status individuals have greater PC1 values than those of low status.</p>
<p>The high-status group showed a higher mean PC1 (0.0186) compared to the low-status group (0.0103), suggesting an enrichment of Eastern Eurasian genetic ancestry among elite individuals in this dataset.</p>
<p><em>The same as in paper: (P = 0.032 for one-sided Welch’s t test to test the null hypothesis that PC1 mean of high-status individuals is equal to that of low-status individuals).</em></p>
</section>
<section id="brown-forsythe-test" class="level3">
<h3 class="anchored" data-anchor-id="brown-forsythe-test">Brown-Forsythe test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>status_test_df<span class="sc">$</span>Status <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(status_test_df<span class="sc">$</span>Status)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>levene_result <span class="ot">&lt;-</span> <span class="fu">leveneTest</span>(PC1 <span class="sc">~</span> Status, <span class="at">data =</span> status_test_df, <span class="at">center =</span> median)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(levene_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)  
group  1  8.3269 0.01076 *
      16                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>To assess whether the high- and low-status groups differed in the variance of their PC1 values the Brown–Forsythe test was performed, which is a version of Levene’s test that uses the median as the center of each group.</p>
<p>The test result showed p-value = 0.01076.</p>
<p>There is statistically significant difference in variance between the two groups.</p>
<p>Thespread or variability of PC1 values is also different between high and low-status individuals. Like, one group may have more heterogeneity in ancestry composition than the other.</p>
<p><em>Paper result: (P = 0.011 for Brown-Forsythe test to compare the PC1 variances of low-status and high-status individuals)</em></p>
</section>
<section id="boxplot-of-pc1" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-of-pc1">Boxplot of PC1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(status_test_df, <span class="fu">aes</span>(<span class="at">x =</span> Status, <span class="at">y =</span> PC1, <span class="at">fill =</span> Status)) <span class="sc">+</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"low"</span> <span class="ot">=</span> <span class="st">"yellow"</span>, <span class="st">"high"</span> <span class="ot">=</span> <span class="st">"green"</span>)) <span class="sc">+</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PC1 by Social Status"</span>, <span class="at">y =</span> <span class="st">"PC1 (Eastern Ancestry)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Plot from the paper Figure 4, last boxplot showing status by PC1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/sciadv_f4_boxplot.jpg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/sciadv_f4_boxplot.jpg" class="img-fluid figure-img" width="2160"></p>
</figure>
</div>
</div>
</div>
<p>I replicated their extra comparison analyses regarding to the site:</p>
<p><em>From paper: On the basis of the broad distribution of SBB and TAK individuals along the PC1 axis, we find that each site is highly heterogeneous. To statistically compare the genetic diversity of each site and the Xiongnu as a whole (“all Xiongnu”), we applied the Brown-Forsythe test for the null hypothesis that two groups have equal PC1 variances (data file S1D). TAK is highly heterogeneous to the level indistinguishable from the variance across all Xiongnu individuals (P = 0.622), while SBB shows less diversity than all Xiongnu (P = 0.030).</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#for comparing with all Xiongnu</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>pca_df <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Site =</span> <span class="fu">case_when</span>(</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>           <span class="fu">str_starts</span>(SampleID, <span class="st">"TAK"</span>) <span class="sc">~</span> <span class="st">"TAK"</span>,</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">str_starts</span>(SampleID, <span class="st">"SBB"</span>) <span class="sc">~</span> <span class="st">"SBB"</span>,</span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>           Pop <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"earlyXiongnu"</span>, <span class="st">"lateXiongnu"</span>, <span class="st">"lateXiongnu_han"</span>, <span class="st">"lateXiongnu_sarmatian"</span>) <span class="sc">~</span> <span class="st">"Xiongnu"</span>,</span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>           <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>         ))</span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>xiongnu_all <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Site <span class="sc">==</span> <span class="st">"Xiongnu"</span>)</span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>tak_df <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span></span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Site <span class="sc">==</span> <span class="st">"TAK"</span>)</span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>tak_vs_xiongnu <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a>  xiongnu_all <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SiteGroup =</span> <span class="st">"Xiongnu"</span>),</span>
<span id="cb101-18"><a href="#cb101-18" aria-hidden="true" tabindex="-1"></a>  tak_df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SiteGroup =</span> <span class="st">"TAK"</span>)</span>
<span id="cb101-19"><a href="#cb101-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb101-20"><a href="#cb101-20" aria-hidden="true" tabindex="-1"></a>tak_vs_xiongnu<span class="sc">$</span>SiteGroup <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(tak_vs_xiongnu<span class="sc">$</span>SiteGroup)</span>
<span id="cb101-21"><a href="#cb101-21" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(PC1 <span class="sc">~</span> SiteGroup, <span class="at">data =</span> tak_vs_xiongnu, <span class="at">center =</span> median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.2675 0.6102
      22               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>sbb_df <span class="ot">&lt;-</span> pca_df <span class="sc">|&gt;</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Site <span class="sc">==</span> <span class="st">"SBB"</span>)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>sbb_vs_xiongnu <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  xiongnu_all <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SiteGroup =</span> <span class="st">"Xiongnu"</span>),</span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  sbb_df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SiteGroup =</span> <span class="st">"SBB"</span>)</span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>sbb_vs_xiongnu<span class="sc">$</span>SiteGroup <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(sbb_vs_xiongnu<span class="sc">$</span>SiteGroup)</span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(PC1 <span class="sc">~</span> SiteGroup, <span class="at">data =</span> sbb_vs_xiongnu, <span class="at">center =</span> median)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)    
group  1  19.765 0.00017 ***
      24                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Individuals from the TAK site (p.value = 0.6102) and those from Xiongnu-associated groups show similar levels of variation in PC1.</p>
<p>While SBB shows less diversity.</p>
<p>Despite my efforts, handling full-genome data locally was infeasible. The <code>.geno</code> file was huge and required server-based tools. At first, I tried to make small subset of individuals to run pca on R, but it was impossible to load the initial data. I wanted to run prcomp on small data but 500k SNP data was too much for my limited memory and computing power. So, after I decided to follow as author’s method on Eigensoft using smartpca.</p>
<p>The trends observed in PCA and the significance of t-tests aligned well with those in the paper. I confirmed higher PC1 values in elite individuals and significant variance differences using R.</p>
<p>*<em>GitHub does not allow uploading files larger than 100MB. For this reason, I could not include the .geno files for the TAK_SBB and v54.1.p1_HO_public datasets in this repository.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>